netlify.toml – with environment variables

Generated 2025‑06‑25

-------------------------------------------------------------

1. Build settings – adjust to your framework

2. Environment variables injected at build time (secure values

should be set in Netlify UI or via netlify env:set CLI).

3. Functions + redirect mapping REST‑like endpoint to serverless

function.

-------------------------------------------------------------

###############################################################################

Build & environment

###############################################################################
[build]
command = "npm run build"   # e.g. vite build / astro build / react‑scripts build
publish  = "dist"           # folder containing final HTML/CSS/JS

--- Build‑time env vars (placeholders) ---

[build.environment]
# Admin credentials (use Netlify UI or CLI to set real values!)
VITE_ADMIN_USERNAME  = "admin"
VITE_ADMIN_EMAIL     = "admin@example.com"
VITE_ADMIN_FULLNAME  = "Admin User"

# NEVER commit real secrets – leave these blank here and
# add secure values in the Netlify dashboard instead.
VITE_ADMIN_PASSWORD  = ""
VITE_API_BEARER_TOKEN = ""

###############################################################################

Serverless functions directory

###############################################################################
[functions]
directory = "netlify/functions"

###############################################################################

Redirects – map pretty API route to serverless function

###############################################################################
[[redirects]]
from   = "/api/admin/create-admin"
to     = "/.netlify/functions/admin-create"
status = 200

###############################################################################

Security / cache / PWA headers (same as before)

###############################################################################
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options         = "DENY"
X-XSS-Protection        = "1; mode=block"
X-Content-Type-Options  = "nosniff"
Referrer-Policy         = "strict-origin-when-cross-origin"

[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "*.js"
[headers.values]
Content-Type = "application/javascript; charset=utf-8"

[[headers]]
for = "*.css"
[headers.values]
Content-Type = "text/css; charset=utf-8"

PWA support

[[headers]]
for = "/manifest.json"
[headers.values]
Content-Type = "application/manifest+json"

[[headers]]
for = "/sw.js"
[headers.values]
Content-Type = "application/javascript"
Cache-Control = "no-cache"
