# netlify.toml – generated 2025‑06‑25

\###############################################################################

# Build settings – adjust to match your framework / tooling

\###############################################################################
\[build]

# If you use Astro, Vite, React, etc. make sure the build script exists

command = "npm run build"

# Folder that contains the final HTML/CSS/JS after build completes

publish = "dist"

\###############################################################################

# Serverless functions directory

\###############################################################################
\[functions]
directory = "netlify/functions"

\###############################################################################

# Redirect rules

\###############################################################################

# 1. API route → Netlify Function

\[\[redirects]]
from = "/api/admin/create-admin"
to   = "/.netlify/functions/admin-create"
status = 200

# 2. SPA fallback (React‑Router / Vue‑Router / Astro‑SPA, etc.)

\[\[redirects]]
from = "/\*"
to   = "/index.html"
status = 200

\###############################################################################

# Security, MIME‑type & caching headers

\###############################################################################
\[\[headers]]
for = "/\*"
\[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

\[\[headers]]
for = "/assets/\*"
\[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

\[\[headers]]
for = "\*.js"
\[headers.values]
Content-Type = "application/javascript; charset=utf-8"

\[\[headers]]
for = "\*.css"
\[headers.values]
Content-Type = "text/css; charset=utf-8"

# Progressive Web App support files

\[\[headers]]
for = "/manifest.json"
\[headers.values]
Content-Type = "application/manifest+json"

\[\[headers]]
for = "/sw\.js"
\[headers.values]
Content-Type = "application/javascript"
Cache-Control = "no-cache"
